-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg1KSseRgz4VT/IQ2U
Dcjl3cOCeU3eN5czW9DEyD+tDeShRANCAAR7/dMRAZZQopHxFBfrAvmD5ZNIrWMB
/U53TDSMGLmLCDEK0zYdzf9XNX2Cu+xQGcaB7498tLu/jwjZfqvYhzMU
-----END PRIVATE KEY-----