-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgD2yFMEbpCdXRr+Bi
BqXCfIa7FWYtZK36KP2FZBcdppmgCgYIKoZIzj0DAQehRANCAAQSKKxJ4WfAySDE
3gwWNuj6bpRxy+JeGqZ0n0aoPkHHntM3f7VNAgr9jdSY0ltl/mFAUL+agzzOXnf5
xMvb9qjG
-----END PRIVATE KEY-----