workflows:
  ios_testflight:
    name: iOS TestFlight (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: latest
      groups:
        - ios_testflight

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.quantumwebdynamics.medisynclabs.dev

      vars:
        BUNDLE_ID: "com.quantumwebdynamics.medisynclabs.dev"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        CONFIGURATION: "Release"

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          xcodebuild -version

      - name: Install dependencies
        script: |
          npm ci

      - name: Ensure TypeScript exists (required for capacitor.config.ts)
        script: |
          npm ls typescript || npm i -D typescript

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Force bundle id in iOS native project
        script: |
          set -euo pipefail

          echo "Forcing bundle id to: ${BUNDLE_ID}"

          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ${BUNDLE_ID}" ios/App/App/App/Info.plist || true

          PBX="ios/App/App.xcodeproj/project.pbxproj"
          if [ -f "$PBX" ]; then
            sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" "$PBX"
          else
            echo "Missing project.pbxproj at $PBX"
            exit 1
          fi

          echo "Bundle IDs now set to:"
          grep -n "PRODUCT_BUNDLE_IDENTIFIER" "$PBX" | head -n 20 || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ios/App/App/App/Info.plist || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: Restore App Store Connect API key
        script: |
          set -euo pipefail
          if [ -z "${APP_STORE_CONNECT_API_KEY_BASE64:-}" ]; then
            echo "Missing APP_STORE_CONNECT_API_KEY_BASE64 env var."
            exit 1
          fi

          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 -D > "$CM_BUILD_DIR/AuthKey_M798L583DA.p8" 2>/dev/null || \
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode > "$CM_BUILD_DIR/AuthKey_M798L583DA.p8"

          ls -la "$CM_BUILD_DIR/AuthKey_M798L583DA.p8"
          head -n 1 "$CM_BUILD_DIR/AuthKey_M798L583DA.p8" || true

      - name: Verify Xcode workspace and schemes
        script: |
          set -euo pipefail
          if [ ! -d "$WORKSPACE" ]; then
            echo "Workspace not found at: $WORKSPACE"
            ls -la ios/App || true
            exit 1
          fi
          xcodebuild -list -workspace "$WORKSPACE"

      - name: Apply Codemagic code signing profiles
        script: |
          set -euo pipefail
          xcode-project use-profiles
          echo "Installed provisioning profiles:"
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Pick provisioning profile for DEV bundle
        script: |
          set -euo pipefail

          echo "Looking for provisioning profile for ${BUNDLE_ID}..."

          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          ls -la "$PROFILES_DIR" || true

          pick=""
          PROFILE_NAME=""
          PROFILE_UUID=""

          for f in "$PROFILES_DIR"/*.mobileprovision; do
            echo "---- Checking: $f"
            plist="$(/usr/bin/security cms -D -i "$f")"

            app_id="$(echo "$plist" | /usr/bin/plutil -extract Entitlements.application-identifier raw -o - - 2>/dev/null || true)"
            name="$(echo "$plist" | /usr/bin/plutil -extract Name raw -o - - 2>/dev/null || true)"
            uuid="$(echo "$plist" | /usr/bin/plutil -extract UUID raw -o - - 2>/dev/null || true)"

            echo "Name: ${name}"
            echo "UUID: ${uuid}"
            echo "AppID: ${app_id}"

            if echo "$app_id" | grep -q "\.${BUNDLE_ID}$"; then
              pick="$f"
              PROFILE_NAME="$name"
              PROFILE_UUID="$uuid"
              echo "✅ MATCH (exact)"
              break
            fi

            if echo "$app_id" | grep -q "${BUNDLE_ID}$"; then
              pick="$f"
              PROFILE_NAME="$name"
              PROFILE_UUID="$uuid"
              echo "✅ MATCH"
              break
            fi
          done

          if [ -z "${pick:-}" ]; then
            echo "❌ No provisioning profile matched ${BUNDLE_ID}."
            exit 1
          fi

          echo "✅ Using provisioning profile file: $pick"
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          echo "Provisioning profile name: $PROFILE_NAME"
          echo "Provisioning profile UUID: $PROFILE_UUID"

      - name: Build archive
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            PROVISIONING_PROFILE="$PROFILE_UUID" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail

          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>

            <key>teamID</key>
            <string>${TEAM_ID}</string>

            <key>signingStyle</key>
            <string>manual</string>

            <key>signingCertificate</key>
            <string>Apple Distribution</string>

            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${PROFILE_NAME}</string>
            </dict>

            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          echo "===== ExportOptions.plist ====="
          cat "$CM_BUILD_DIR/ExportOptions.plist"

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ipa"

          echo "Exported files:"
          ls -la "$CM_BUILD_DIR/build/ipa" || true

      - name: Upload to TestFlight (manual)
        script: |
          set -euo pipefail

          IPA_PATH="$CM_BUILD_DIR/build/ipa/App.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            echo "IPA not found at: $IPA_PATH"
            ls -la "$CM_BUILD_DIR/build/ipa" || true
            exit 1
          fi

          KEY_PATH="$CM_BUILD_DIR/AuthKey_M798L583DA.p8"
          if [ ! -f "$KEY_PATH" ]; then
            echo "Missing .p8 key at: $KEY_PATH"
            exit 1
          fi

          head -n 2 "$KEY_PATH" || true
          if ! grep -q "BEGIN PRIVATE KEY" "$KEY_PATH"; then
            echo "Key file does not look like PEM."
            sed -n '1,5p' "$KEY_PATH" || true
            exit 1
          fi

          export APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY="$(cat "$KEY_PATH")"

          app-store-connect publish \
            --path "$IPA_PATH" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key @env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY \
            --testflight \
            --platform IOS

    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Logs/**/*
      - $CM_BUILD_DIR/build/**/*.xcarchive