workflows:
  ios-release:
    name: iOS Release (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.quantumwebdynamics.medisynclabs
      groups:
        - ios_signing

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: List installed provisioning profiles
        script: |
          echo "=== Provisioning profiles on builder ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          for f in "$HOME/Library/MobileDevice/Provisioning Profiles"/*.mobileprovision; do
            echo "---- $f"
            security cms -D -i "$f" | /usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin
            security cms -D -i "$f" | /usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin
            security cms -D -i "$f" | /usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin
          done || true

      - name: Build Archive (Xcode)
        script: |
          # ⚠️ After the previous step prints UUID, paste it here:
          PROFILE_UUID="PASTE_UUID_HERE"

          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath /Users/builder/clone/build/App.xcarchive \
            DEVELOPMENT_TEAM=L5GY5W76NG \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="$PROFILE_UUID" \
            archive

    artifacts:
      - /Users/builder/clone/build/*.xcarchive
      - ios/App/build/**/*.log
      - $HOME/Library/Logs/DiagnosticReports/**/*.crash