workflows:
  ios-release:
    name: iOS Release (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: latest

      # ✅ Tell Codemagic to pull/install signing assets for this workflow
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.quantumwebdynamics.medisynclabs

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: Build Archive (Xcode)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath /Users/builder/clone/build/App.xcarchive \
            DEVELOPMENT_TEAM=L5GY5W76NG \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            archive

      # ✅ Export an IPA (needed for TestFlight/App Store upload)
      - name: Export IPA
        script: |
          cat > /Users/builder/clone/exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>L5GY5W76NG</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          PLIST

          mkdir -p /Users/builder/clone/build/export

          xcodebuild -exportArchive \
            -archivePath /Users/builder/clone/build/App.xcarchive \
            -exportPath /Users/builder/clone/build/export \
            -exportOptionsPlist /Users/builder/clone/exportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - /Users/builder/clone/build/export/*.ipa
      - /Users/builder/clone/build/*.xcarchive
      - ios/App/build/**/*.log
      - $HOME/Library/Logs/DiagnosticReports/**/*.crash