workflows:
  ios_testflight:
    name: iOS TestFlight (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: latest
      groups:
        - ios_testflight

      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        CONFIGURATION: "Release"

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          xcodebuild -version

      - name: Install dependencies
        script: |
          npm ci

      - name: Ensure TypeScript exists (required for capacitor.config.ts)
        script: |
          npm ls typescript || npm i -D typescript

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      # ---- App Store Connect API Key (.p8) via base64 env var ----
      - name: Restore App Store Connect API key
        script: |
          set -euo pipefail
          if [ -z "${APP_STORE_CONNECT_API_KEY_BASE64:-}" ]; then
            echo "Missing APP_STORE_CONNECT_API_KEY_BASE64 env var."
            exit 1
          fi

          # macOS base64 uses -D; GNU uses --decode. Try both.
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 -D > "$CM_BUILD_DIR/AuthKey_M798L583DA.p8" 2>/dev/null || \
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode > "$CM_BUILD_DIR/AuthKey_M798L583DA.p8"

          ls -la "$CM_BUILD_DIR/AuthKey_M798L583DA.p8"

      - name: Verify Xcode workspace and schemes
        script: |
          set -euo pipefail
          if [ ! -d "$WORKSPACE" ]; then
            echo "Workspace not found (dir) at: $WORKSPACE"
            echo "Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi
          xcodebuild -list -workspace "$WORKSPACE"

      - name: Apply Codemagic code signing profiles + detect App Store profile
        script: |
          set -euo pipefail
          xcode-project use-profiles

          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "Provisioning profiles dir: $PROFILES_DIR"
          ls -la "$PROFILES_DIR" || true

          echo "Searching for a profile that matches bundle id: $BUNDLE_ID"
          MATCH_FILE=""

          for f in "$PROFILES_DIR"/*.mobileprovision; do
            # Extract the application-identifier from the profile
            APP_ID=$(/usr/bin/security cms -D -i "$f" \
              | /usr/bin/plutil -extract Entitlements.application-identifier raw -o - - 2>/dev/null || true)

            if echo "$APP_ID" | grep -q "\.$BUNDLE_ID$"; then
              MATCH_FILE="$f"
              echo "Matched profile file: $MATCH_FILE"
              echo "application-identifier: $APP_ID"
              break
            fi
          done

          if [ -z "$MATCH_FILE" ]; then
            echo "❌ No installed provisioning profile matched bundle id $BUNDLE_ID"
            echo "Dumping application-identifiers found:"
            for f in "$PROFILES_DIR"/*.mobileprovision; do
              APP_ID=$(/usr/bin/security cms -D -i "$f" \
                | /usr/bin/plutil -extract Entitlements.application-identifier raw -o - - 2>/dev/null || true)
              echo "$(basename "$f") -> $APP_ID"
            done
            exit 1
          fi

          PROFILE_NAME=$(/usr/bin/security cms -D -i "$MATCH_FILE" \
            | /usr/bin/plutil -extract Name raw -o - -)

          echo "✅ Using provisioning profile name (specifier): $PROFILE_NAME"
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV

      - name: Build archive (force Apple Distribution + detected profile)
        script: |
          set -euo pipefail
          echo "Using PROFILE_NAME=$PROFILE_NAME"

          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail
          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ipa"

    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Logs/**/*
      - $CM_BUILD_DIR/build/**/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $CM_BUILD_DIR/AuthKey_M798L583DA.p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true