workflows:
  ios-release:
    name: iOS Release (Capacitor) - TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: latest

      vars:
        BUNDLE_ID: "com.quantumwebdynamics.medisynclabs"
        TEAM_ID: "L5GY5W76NG"
        APP_SCHEME: "App"
        WORKSPACE: "ios/App/App.xcworkspace"

        # These are set in Codemagic UI as Environment variables
        # P12_PASSWORD
        # ASC_KEY_ID
        # ASC_ISSUER_ID

    scripts:
      - name: Install NPM dependencies
        script: |
          npm ci

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      # ---- Secure files: Codemagic downloads secure files into $CM_BUILD_DIR by default ----
      - name: Install signing assets (p12 + mobileprovision)
        script: |
          set -euo pipefail

          echo "CM_BUILD_DIR=$CM_BUILD_DIR"
          ls -la "$CM_BUILD_DIR"

          # Names MUST match what you uploaded as Secure Files
          P12_PATH="$CM_BUILD_DIR/apple_distribution2.p12"
          PROFILE_PATH="$CM_BUILD_DIR/MediSync_App_Store_Profile.mobileprovision"

          if [ ! -f "$P12_PATH" ]; then
            echo "❌ Missing p12 at $P12_PATH"
            exit 1
          fi

          if [ ! -f "$PROFILE_PATH" ]; then
            echo "❌ Missing profile at $PROFILE_PATH"
            exit 1
          fi

          # Import p12 into keychain
          KEYCHAIN_PATH="$HOME/Library/Keychains/build.keychain-db"
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

          security import "$P12_PATH" \
            -k "$KEYCHAIN_PATH" \
            -P "$P12_PASSWORD" \
            -T /usr/bin/codesign \
            -T /usr/bin/security

          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" "$KEYCHAIN_PATH"

          # Install provisioning profile
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/"

          # Extract UUID for reliable manual signing
          PROFILE_UUID=$(security cms -D -i "$PROFILE_PATH" | /usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin)
          PROFILE_NAME=$(security cms -D -i "$PROFILE_PATH" | /usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin)

          echo "✅ Installed profile: $PROFILE_NAME"
          echo "✅ Profile UUID: $PROFILE_UUID"

          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV

      - name: Build Archive (App Store signing)
        script: |
          set -euo pipefail

          mkdir -p build

          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$APP_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="$PROFILE_UUID" \
            archive \
            CODE_SIGNING_ALLOWED[Pods-App]=NO \
            CODE_SIGNING_ALLOWED[Capacitor]=NO \
            CODE_SIGNING_ALLOWED[CapacitorCordova]=NO

      - name: Export IPA
        script: |
          set -euo pipefail

          cat > "$CM_BUILD_DIR/exportOptions.plist" <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>$TEAM_ID</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          PLIST

          mkdir -p "$CM_BUILD_DIR/build/export"

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/export" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist"

          ls -la "$CM_BUILD_DIR/build/export"

      - name: Upload to TestFlight (App Store Connect API key)
        script: |
          set -euo pipefail

          IPA_PATH=$(ls "$CM_BUILD_DIR/build/export"/*.ipa | head -n 1)
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ No IPA found to upload."
            exit 1
          fi

          # Secure file (AuthKey_*.p8) should be in $CM_BUILD_DIR if uploaded as Secure file
          ASC_KEY_FILE="$CM_BUILD_DIR/AuthKey_${ASC_KEY_ID}.p8"
          if [ ! -f "$ASC_KEY_FILE" ]; then
            echo "❌ Missing App Store Connect API key file at $ASC_KEY_FILE"
            exit 1
          fi

          xcrun altool --upload-app \
            --type ios \
            --file "$IPA_PATH" \
            --apiKey "$ASC_KEY_ID" \
            --apiIssuer "$ASC_ISSUER_ID" \
            --verbose

    artifacts:
      - build/export/*.ipa
      - build/*.xcarchive
      - ios/App/build/**/*.log
      - $HOME/Library/Logs/DiagnosticReports/**/*.crash