workflows:
  ios_testflight:
    name: iOS TestFlight (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: latest
      groups:
        - ios_testflight

      vars:
        # Safe defaults (these can be overridden by your variable group if you want)
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        CONFIGURATION: "Release"

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          xcodebuild -version

      - name: Install dependencies
        script: |
          npm ci

      - name: Ensure TypeScript exists (required for capacitor.config.ts)
        script: |
          npm ls typescript || npm i -D typescript

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      # ---- App Store Connect API Key (.p8) via base64 env var ----
      # You MUST add this in your variable group as a Secret:
      #   APP_STORE_CONNECT_API_KEY_BASE64 = <base64 of AuthKey_M798L583DA.p8>
      - name: Restore App Store Connect API key
        script: |
          set -euo pipefail
          if [ -z "${APP_STORE_CONNECT_API_KEY_BASE64:-}" ]; then
            echo "Missing APP_STORE_CONNECT_API_KEY_BASE64 env var."
            exit 1
          fi
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode > "$CM_BUILD_DIR/AuthKey_M798L583DA.p8"
          ls -la "$CM_BUILD_DIR/AuthKey_M798L583DA.p8"

      # Optional: quick sanity checks so failures are obvious
      - name: Verify Xcode workspace and schemes
        script: |
          set -euo pipefail
          if [ ! -f "$WORKSPACE" ]; then
            echo "Workspace not found at: $WORKSPACE"
            echo "Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi
          xcodebuild -list -workspace "$WORKSPACE"

      - name: Build archive
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail
          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ipa"

    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Logs/**/*
      - $CM_BUILD_DIR/build/**/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $CM_BUILD_DIR/AuthKey_M798L583DA.p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true